exclude: "bin/executable_diff-so-fancy"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(yaml|yml)$
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.0
    hooks:
      - id: pycln
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck
        types_or: ["shell", "bash", "sh"]
      - id: shfmt
        types_or: ["shell", "bash", "sh", "zsh"]
