#!/bin/zsh
#
# Make sure to put anything that modifies the PATH here. This way PATH is not
# modified when ~/.zshrc is sourced.

PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PATH="$HOME/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/local_bin:$PATH"

export PATH="$PYENV_ROOT/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"

# Go installs packages here
export GOPATH="$HOME"/go
export GOBIN="$GOPATH"/bin
export PATH="$GOBIN":"$PATH"
export GO111MODULE=on

export PATH="$HOME"/.cargo/bin:"$PATH"

export PATH=/usr/local/opt/postgresql@11/bin:"$PATH"
export PATH="$(antibody path bigH/git-fuzzy)"/bin:$PATH

export CODE="${HOME}/code"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh" # This loads nvm

# ------------------------------------------------------------------------------
# -----------------------------------plugins------------------------------------
# ------------------------------------------------------------------------------

source ~/.zsh_plugins.sh
