#!/bin/bash

# Watch all files in the "CODE" directory and commits them to the WIP git index
# if they are contained in a git repo.
# Uses: https://github.com/bartman/git-wip

_git_wip() {
	file=$1
	DIR=$(dirname "$file")
	if git -C "$DIR" rev-parse >/dev/null 2>&1; then
		git -C "$DIR" wip save -u "$file via file watcher"
		echo "Saved $file in $(git -C "$DIR" wip info)"
	else
		echo "$file is not in a git repo, not saving"
	fi
}

fswatch -0 --event IsFile -e '.*\.git.*' /Users/brian/code | while read -r -d "" file; do
	_git_wip "$file"
done
