# ~/.config/starship.toml
format = """
$username\
$hostname\
$localip\
$directory\
$memory_usage\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$character"""


[nodejs]
disabled=true

[aws]
disabled=true

[gcloud]
disabled=true

[buf]
disabled=true

[kubernetes]
format = '[$context]($style)'
disabled=true
contexts = [
  { context_pattern = "tecton.teleport.sh-(?P<cluster>.+)", context_alias="⛵ $cluster ", style = "green" },
  { context_pattern = "orbstack", context_alias="", style = "" },
]

[custom.teleport-aws]
disabled=true
format=' [$symbol ($output) ]($style)'
command = 'tsh apps config -f json | jq -r ".aws_role_arn | split(\"/\")[-1]"'
when='[ -n "$(tsh apps config -f json | jq -r ".aws_role_arn | split(\"/\")[-1]")" ]'
symbol = '☁️'
