# ~/.config/starship.toml

[aws]
disabled=true

[gcloud]
disabled=true

[kubernetes]
disabled=false
contexts = [
  { context_pattern = "tecton.teleport.sh-(?P<cluster>.+)", context_alias="$cluster", style = "green" },
  { context_pattern = "orbstack", disabled=true},
]

[custom.teleport-aws]
format='on [$symbol ($output) ]($style)'
command = 'tsh apps config -f json | jq -r ".aws_role_arn | split(\"/\")[-1]"'
when=true
symbol = '☁️ '
